var query = $('#page0').attr("href");//1
var query1 = $('#page1').attr("href");//2
var query2 = $('#page2').attr("href");//3
var query3 = $('#page3').attr("href");//4
var query4 = $('#page4').attr("href");//5
var query5 = $('#page5').attr("href");
var query6 = $('#page6').attr("href");
var query7 = $('#page7').attr("href");
var query8 = $('#page8').attr("href");
var query9 = $('#page9').attr("href");
var query10 = $('#page10').attr("href");
var query11 = $('#page11').attr("href");
var query12 = $('#page12').attr("href");
var query13 = $('#page13').attr("href");
var query14 = $('#page14').attr("href");
var query15 = $('#page15').attr("href");
var query16 = $('#page16').attr("href");
var query17 = $('#page17').attr("href");
var query18 = $('#page18').attr("href");
var query19 = $('#page19').attr("href");
var query20 = $('#page20').attr("href");
var query21 = $('#page21').attr("href");
var query22 = $('#page22').attr("href");
var query23 = $('#page23').attr("href");
var query24 = $('#page24').attr("href");
var query25 = $('#page25').attr("href");
var query26 = $('#page26').attr("href");
var query27 = $('#page27').attr("href");
var query28 = $('#page28').attr("href");
var query29 = $('#page29').attr("href");
var query30 = $('#page30').attr("href");
var query31 = $('#page31').attr("href");
var query32 = $('#page32').attr("href");
var query33 = $('#page33').attr("href");
var query34 = $('#page34').attr("href");
var query35 = $('#page35').attr("href");
var query36 = $('#page36').attr("href");
var query37 = $('#page37').attr("href");
var query38 = $('#page38').attr("href");
var query39 = $('#page39').attr("href");
var query40 = $('#page40').attr("href");
var query41 = $('#page41').attr("href");
var query42 = $('#page42').attr("href");
var query43 = $('#page43').attr("href");
var query44 = $('#page44').attr("href");
var query45 = $('#page45').attr("href");
var query46 = $('#page46').attr("href");
var query47 = $('#page47').attr("href");
var query48 = $('#page48').attr("href");
var query49 = $('#page49').attr("href");
var query50 = $('#page50').attr("href");
var query51 = $('#page51').attr("href");
var query52 = $('#page52').attr("href");
var query53 = $('#page53').attr("href");
var query54 = $('#page54').attr("href");
var query55 = $('#page55').attr("href");
var query56 = $('#page56').attr("href");
var query57 = $('#page57').attr("href");
var query58 = $('#page58').attr("href");
var query59 = $('#page59').attr("href");
var query60 = $('#page60').attr("href");
var query61 = $('#page61').attr("href");
var query62 = $('#page62').attr("href");
var query63 = $('#page63').attr("href");
var query64 = $('#page64').attr("href");
var query65 = $('#page65').attr("href");
var query66 = $('#page66').attr("href");
window.onload = function () {
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    pushHistory();
    window.addEventListener("popstate",function (ev) {
        window.history.go(this.url)
    },false);
};
function pushHistory(e) {
    var state = {
        title: "title",
        url: e
    };
    window.history.pushState(state, "title", e);
}
