window.onload = function () {
    pushHistory();
};
var pushHistory = function () {
    var query = $('#page0').attr("href");//1
    console.log(query);
    var query1 = $('#page1').attr("href");//2
    console.log(query1);
    var query2 = $('#page2').attr("href");//3
    console.log(query2);
    var query3 = $('#page3').attr("href");//4
    console.log(query3);
    var query4 = $('#page4').attr("href");//5
    console.log(query4);
    var query5 = $('#page5').attr("href");
    console.log(query5);
    var query6 = $('#page6').attr("href");
    console.log(query6);
    var query7 = $('#page7').attr("href");
    console.log(query7);
    var query8 = $('#page8').attr("href");
    console.log(query8);
    var query9 = $('#page9').attr("href");
    console.log(query9);
    var query10 = $('#page10').attr("href");
    console.log(query10);
    var query11 = $('#page11').attr("href");
    console.log(query11);
    var query12 = $('#page12').attr("href");
    console.log(query12);
    var query13 = $('#page13').attr("href");
    console.log(query13);
    var query14 = $('#page14').attr("href");
    console.log(query14);
    var query15 = $('#page15').attr("href");
    console.log(query15);
    var query16 = $('#page16').attr("href");
    console.log(query16);
    var query17 = $('#page17').attr("href");
    console.log(query17);
    var query18 = $('#page18').attr("href");
    console.log(query18);
    var query19 = $('#page19').attr("href");
    console.log(query19);
    var query20 = $('#page20').attr("href");
    console.log(query20);
    var query21 = $('#page21').attr("href");
    console.log(query21);
    var query22 = $('#page22').attr("href");
    console.log(query22);
    var query23 = $('#page23').attr("href");
    console.log(query23);
    var query24 = $('#page24').attr("href");
    console.log(query24);
    var query25 = $('#page25').attr("href");
    console.log(query25);
    var query26 = $('#page26').attr("href");
    console.log(query26);
    var query27 = $('#page27').attr("href");
    console.log(query27);
    var query28 = $('#page28').attr("href");
    console.log(query28);
    var query29 = $('#page29').attr("href");
    console.log(query29);
    var query30 = $('#page30').attr("href");
    console.log(query30);
    var query31 = $('#page31').attr("href");
    console.log(query31);
    var query32 = $('#page32').attr("href");
    console.log(query32);
    var query33 = $('#page33').attr("href");
    console.log(query33);
    var query34 = $('#page34').attr("href");
    console.log(query34);
    var query35 = $('#page35').attr("href");
    console.log(query35);
    var query36 = $('#page36').attr("href");
    console.log(query36);
    var query37 = $('#page37').attr("href");
    console.log(query37);
    var query38 = $('#page38').attr("href");
    console.log(query38);
    var query39 = $('#page39').attr("href");
    console.log(query39);
    var query40 = $('#page40').attr("href");
    console.log(query40);
    var query41 = $('#page41').attr("href");
    console.log(query41);
    var query42 = $('#page42').attr("href");
    console.log(query42);
    var query43 = $('#page43').attr("href");
    console.log(query43);
    var query44 = $('#page44').attr("href");
    console.log(query44);
    var query45 = $('#page45').attr("href");
    console.log(query45);
    var query46 = $('#page46').attr("href");
    console.log(query46);
    var query47 = $('#page47').attr("href");
    console.log(query47);
    var query48 = $('#page48').attr("href");
    console.log(query48);
    var query49 = $('#page49').attr("href");
    console.log(query49);
    var query50 = $('#page50').attr("href");
    console.log(query50);
    var query51 = $('#page51').attr("href");
    console.log(query51);
    var query52 = $('#page52').attr("href");
    console.log(query52);
    var query53 = $('#page53').attr("href");
    console.log(query53);
    var query54 = $('#page54').attr("href");
    console.log(query54);
    var query55 = $('#page55').attr("href");
    console.log(query55);
    var query56 = $('#page56').attr("href");
    console.log(query56);
    var query57 = $('#page57').attr("href");
    console.log(query57);
    var query58 = $('#page58').attr("href");
    console.log(query58);
    var query59 = $('#page59').attr("href");
    console.log(query59);
    var query60 = $('#page60').attr("href");
    console.log(query60);
    var query61 = $('#page61').attr("href");
    console.log(query61);
    var query62 = $('#page62').attr("href");
    console.log(query62);
    var query63 = $('#page63').attr("href");
    console.log(query63);
    var query64 = $('#page64').attr("href");
    console.log(query64);
    var query65 = $('#page65').attr("href");
    console.log(query65);
    var query66 = $('#page66').attr("href");
    console.log(query66);

};
